- id: wordwarden
  name: Word Warden
  description: "Find undesired strings before committing, such as breakpoints."
  entry: cargo run --release --bin word_warden
  language: rust
  minimum_pre_commit_version: 3.0.0
  require_serial: false
